permalink:           pretty
relative_permalinks: true
exclude:             [ README.md, Gemfile, vendor, .*, bower.json ]

title:               chapay's blog
tagline:             'Blog about me, tech and web'
description:         Hi everyone! <br/> <br/> This is Andrey Sobkanyuk's personal page.
url:                 http://chapay.com
baseurl:             'http://chapay.com'
paginate:            5

author:
  name:              Andrey Sobkanyuk
  url:               'http://chapay.com'
  email:             hi@chapay.com

repository:          https://github.com/chapay/chapay.github.io
github:              https://github.com/chapay
twitter:             https://twitter.com/chapovod
linkedin:            https://linkedin.com/in/chapay
